---
title: "README for Processed Data Files"
author: "Setu Pelz (pelz@iiasa.ac.at)"
---

# README for Processed Data Files

This README describes the contents of all processed data files.

------------------------------------------------------------------------

## 1. `01_iso3c_miss_to_agg_row.csv`

**Description**\
Contains all countries and territories that do not have complete data across all datasets over the analysis period and are therefore subsequently aggregated into a single Rest of World (ROW) aggregate. Missing countries and territories are presented with selected relevant indicators for the year 2022. This is not an exhaustive list, and does not contain countries and territories that are completely missing across all data sources used (e.g. the State of Palestine, the Vatican City). These are nevertheless aggregated into the ROW region (see next section).

**Columns**

+-------------------------+-------------------------------------------------------------------------------------------------------+
| Column                  | Description                                                                                           |
+=========================+=======================================================================================================+
| **r10**                 | The R10 IAMC region code to which the country or territory belongs.                                   |
+-------------------------+-------------------------------------------------------------------------------------------------------+
| **iso3c**               | ISO 3166-1 alpha-3 country code (3-letter code).                                                      |
+-------------------------+-------------------------------------------------------------------------------------------------------+
| **countryname**         | Name of the country or territory.                                                                     |
+-------------------------+-------------------------------------------------------------------------------------------------------+
| **year**                | The data year (2022).                                                                                 |
+-------------------------+-------------------------------------------------------------------------------------------------------+
| **terr_GtCO2FFI**       | Territorial (production-based) CO2 emissions from fossil fuel and industry (in Gt CO2).               |
+-------------------------+-------------------------------------------------------------------------------------------------------+
| **terr_GtCO2FFI_share** | The share (%) of the total world CO2FFI emissions that this country or territory contributes in 2022. |
+-------------------------+-------------------------------------------------------------------------------------------------------+
| **pop**                 | Population for the country or region in 2022.                                                         |
+-------------------------+-------------------------------------------------------------------------------------------------------+
| **pop_share**           | The share (%) of the total world’s population that this country or territory represents in 2022.      |
+-------------------------+-------------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## 2. `02_iso3c_indicators.csv`

**Description**\
Contains yearly indicator data for all countries and territories with complete data, alongside the aggregate rest of world (ROW) for missing countries and territories. The ROW aggregate is determined by subtracting the sum of all complete countries from known world totals, thus representing all missing countries and territories, including those not present in the missing countries and territories list above.

**Columns**

+-------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Column                  | Description                                                                                                                 |
+=========================+=============================================================================================================================+
| **r10**                 | The R10 IAMC region code to which the country or territory belongs.                                                         |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| **iso3c**               | ISO 3166-1 alpha-3 country code (3-letter code). For the aggregated missing countries: "ROW".                               |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| **year**                | Year.                                                                                                                       |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| **pop**                 | Population.                                                                                                                 |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| **gdpcurrmer**          | GDP (Gross Domestic Product) in current USD at market exchange rates.                                                       |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| **gdpcurrppp**          | GDP in current USD at Purchasing Power Parity (PPP) rates.                                                                  |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| **terr_GtCO2FFI**       | Territorial (production-based) CO2 emissions from fossil fuel and industry (in Gt CO2).                                     |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| **lulucf_GtCO2_mean**   | Average land-use, land-use change, and forestry (LULUCF) CO2 (in Gt CO2) across available estimates (BLUE, H&C2023, OSCAR). |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| **lulucf_GtCO2_blue**   | LULUCF-related CO2 estimate (in Gt CO2) from BLUE (Hansis et al., 2015).                                                    |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| **lulucf_GtCO2_hc2023** | LULUCF-related CO2 estimate (in Gt CO2) from H&C2023 (Houghton and Castanho, 2023).                                         |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| **lulucf_GtCO2_oscar**  | LULUCF-related CO2 estimate (in Gt CO2) from OSCAR (Gasser et al., 2020).                                                   |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## 3. `03_rcbquantities.csv`

**Description**\
Contains remaining carbon budgets (RCBs) in Gt CO2FFI for different start years to net-zero, based on Lamboll et al. (2023) and adjusted with Global Carbon Project data.

**Columns**

+-------------------+---------------------------------------------------------------------------+
| Column            | Description                                                               |
+===================+===========================================================================+
| **rcb**           | Reference period for the remaining carbon budget.                         |
+-------------------+---------------------------------------------------------------------------+
| **terr_GtCO2FFI** | The CO2FFI remaining carbon budget for that reference period (in Gt CO2). |
+-------------------+---------------------------------------------------------------------------+

------------------------------------------------------------------------

## 4. `04_iso3c_rcb19902020gtco2ffi.csv`

**Description**\
Contains territorial fossil fuel and industry CO2 emissions by country and year, plus various remaining carbon budget (RCB) allocations (derived from different start years and allocation approaches). Subtracting one year’s emissions from the RCB yields the next year’s RCB.

**Columns**

+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| Column                  | Description                                                                                                                                            |
+=========================+========================================================================================================================================================+
| **iso3c**               | ISO 3166-1 alpha-3 country code (3-letter code).                                                                                                       |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| **year**                | Year.                                                                                                                                                  |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| **terr_GtCO2FFI**       | Territorial (production-based) CO2 emissions from fossil fuel and industry (in GtCO2) in that year.                                                    |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| **pp2015,**             | Remaining carbon budgets (RCBs) from the start of the year (in Gt CO2FFI) under approaches considering responsibility (start years 2015, 1990, 1850).  |
|                         |                                                                                                                                                        |
| **pp1990,**             |                                                                                                                                                        |
|                         |                                                                                                                                                        |
| **pp1850**              |                                                                                                                                                        |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| **pp\*\_atp_ppp_pf\*,** | Remaining carbon budgets (RCBs) under approaches that consider responsibility and capability, scaled by GDP (PPP/MER) and different penalty functions. |
|                         |                                                                                                                                                        |
| **pp\*\_atp_mer_pf\***  |                                                                                                                                                        |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## 5. `05_r10_rcb19902020gtco2ffi.csv`

**Description**\
Regional remaining carbon budgets under different allocation approaches, presented here from the years 1990–2020.

**Columns**

+--------------------+-------------------------------------------------------------------------------------------------------+
| Column             | Description                                                                                           |
+====================+=======================================================================================================+
| **r10**            | R10 region code.                                                                                      |
+--------------------+-------------------------------------------------------------------------------------------------------+
| **allocation**     | Allocation approach category.                                                                         |
+--------------------+-------------------------------------------------------------------------------------------------------+
| **ppp**            | Defines whether PPP or MER GDP data is used, for allocation approaches that also consider capability. |
+--------------------+-------------------------------------------------------------------------------------------------------+
| **pf**             | Defines which penalty function is used, for allocation approaches that also consider capability.      |
+--------------------+-------------------------------------------------------------------------------------------------------+
| **ppp_pf**         | Combination of **ppp** and **pf** for convenience.                                                    |
+--------------------+-------------------------------------------------------------------------------------------------------+
| **name**           | Combination of **allocation**, **ppp**, and **pf** for convenience.                                   |
+--------------------+-------------------------------------------------------------------------------------------------------+
| **year**           | The year.                                                                                             |
+--------------------+-------------------------------------------------------------------------------------------------------+
| **rcb**            | The remaining carbon budget (in Gt CO2FFI) at the start of that year.                                 |
+--------------------+-------------------------------------------------------------------------------------------------------+
| **pop_yearto2050** | The remaining cumulative population from the current year up to 2050 for that region.                 |
+--------------------+-------------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## 6. `06_r10_ar6_gtco2ffi_processed_scaled.csv`

**Description**\
Contains AR6 scenario CO2FFI emissions pathway data scaled (harmonized) to match recent (2022) historical data. Includes timing of net-zero and peak emissions.

**Columns**

+------------------------+---------------------------------------------------------------------------------+
| Column                 | Description                                                                     |
+========================+=================================================================================+
| **model**              | Model name.                                                                     |
+------------------------+---------------------------------------------------------------------------------+
| **scen**               | Scenario name.                                                                  |
+------------------------+---------------------------------------------------------------------------------+
| **cat**                | IPCC WGIII AR6 scenario temperature category.                                   |
+------------------------+---------------------------------------------------------------------------------+
| **r10**                | R10 region code.                                                                |
+------------------------+---------------------------------------------------------------------------------+
| **year**               | Year.                                                                           |
+------------------------+---------------------------------------------------------------------------------+
| **pop**                | Population for that region and year.                                            |
+------------------------+---------------------------------------------------------------------------------+
| **terr_GtCO2FFI_orig** | Original (un-harmonized) fossil fuel and industry CO2 (FFI) pathway (in GtCO2). |
+------------------------+---------------------------------------------------------------------------------+
| **terr_GtCO2FFI**      | Harmonized FFI pathway (in GtCO2), adjusted to match 2022 historical data.      |
+------------------------+---------------------------------------------------------------------------------+
| **netzeroyear**        | The year in which net-zero CO2FFI emissions occur in the scenario.              |
+------------------------+---------------------------------------------------------------------------------+
| **peakyear**           | The year in which CO2FFI emissions peak in the scenario.                        |
+------------------------+---------------------------------------------------------------------------------+
| **peakyearbin**        | Decadal bin for the peak CO2FFI emissions year.                                 |
+------------------------+---------------------------------------------------------------------------------+
| **netzeroyearbin**     | Decadal bin for the net-zero CO2FFI emissions year.                             |
+------------------------+---------------------------------------------------------------------------------+
| **pkyearbin**          | Numeric peak CO2FFI emissions year bin.                                         |
+------------------------+---------------------------------------------------------------------------------+
| **nzyearbin**          | Numeric net-zero CO2FFI emissions year bin.                                     |
+------------------------+---------------------------------------------------------------------------------+

------------------------------------------------------------------------

## 7. `07_r10_ar6_gtco2ffi_processed_scaled_cmltv.csv`

**Description**\
Describes cumulative AR6 scenario CO2FFI emissions to the year 2100, scaled using 2022 historical data.

**Columns**

+------------------------------+-------------------------------------------------------------------------------------------+
| Column                       | Description                                                                               |
+==============================+===========================================================================================+
| **model**                    | Model name.                                                                               |
+------------------------------+-------------------------------------------------------------------------------------------+
| **scen**                     | Scenario name.                                                                            |
+------------------------------+-------------------------------------------------------------------------------------------+
| **r10**                      | R10 region code.                                                                          |
+------------------------------+-------------------------------------------------------------------------------------------+
| **peakyearbin**              | Decadal bin for the peak CO2FFI emissions year.                                           |
+------------------------------+-------------------------------------------------------------------------------------------+
| **netzeroyearbin**           | Decadal bin for the net-zero CO2FFI emissions year.                                       |
+------------------------------+-------------------------------------------------------------------------------------------+
| **pkyearbin**                | Numeric peak CO2FFI emissions year bin.                                                   |
+------------------------------+-------------------------------------------------------------------------------------------+
| **nzyearbin**                | Numeric net-zero CO2FFI emissions year bin.                                               |
+------------------------------+-------------------------------------------------------------------------------------------+
| **terr_GtCO2FFI_cmltv**      | Cumulative harmonized fossil fuel & industry CO2 emissions (in Gt CO2).                   |
+------------------------------+-------------------------------------------------------------------------------------------+
| **terr_GtCO2FFI_orig_cmltv** | Cumulative original (pre-harmonization) fossil fuel & industry CO2 emissions (in Gt CO2). |
+------------------------------+-------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## 8. `08_r10_ar6_carbondebt_2100_gtco2ffi.csv`

**Description**\
Contains AR6 scenario regional “net-zero carbon debt” accrual under various allocation approaches.

**Columns**

+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Column                          | Description                                                                                                                                                  |
+=================================+==============================================================================================================================================================+
| **model**                       | Model name.                                                                                                                                                  |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **scen**                        | Scenario name.                                                                                                                                               |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **r10**                         | R10 region code.                                                                                                                                             |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **peakyearbin**                 | Decadal bin for the peak emissions year.                                                                                                                     |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **pkyearbin**                   | Numeric peak year.                                                                                                                                           |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **netzeroyearbin**              | Decadal bin for the net-zero emissions year.                                                                                                                 |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **nzyearbin**                   | Numeric net-zero year.                                                                                                                                       |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **allocation**                  | Allocation approach category.                                                                                                                                |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **ppp_pf**                      | Defines whether PPP or MER GDP data is used, for allocation approaches that also consider capability, and which penalty function.                            |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **rcb2100_terr_GtCO2FFI_cmltv** | Regional remaining carbon budget at net-zero CO2-FFI under the specified scenario/allocation (in Gt CO2). A negative value implies a “net-zero carbon debt”. |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## 9. `09_nztargetyears.csv`

**Description**\
Combines information from the Net-Zero Tracker and the Climate Action Tracker data (as of March 2024).

**Columns**

+----------------------------+-----------------------------------------------------------------------------------------------+
| Column                     | Description                                                                                   |
+============================+===============================================================================================+
| **iso3c**                  | ISO 3166-1 alpha-3 country code (3-letter code).                                              |
+----------------------------+-----------------------------------------------------------------------------------------------+
| **end_target_year_comb**   | Our combined net-zero target year (merging Net-Zero Tracker and Climate Action Tracker data). |
+----------------------------+-----------------------------------------------------------------------------------------------+
| **end_target_comb**        | Whether the net-zero target applies to CO2 or all GHGs (combined assessment).                 |
+----------------------------+-----------------------------------------------------------------------------------------------+
| **end_target_status_comb** | Combined status (e.g., “in law”, “in policy document”) of the net-zero target.                |
+----------------------------+-----------------------------------------------------------------------------------------------+
| *Other columns*            | Additional details regarding classification and text descriptors for each net-zero target.    |
+----------------------------+-----------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## 10. `10_r10_curpol_curpledge_impren_emiss.csv`

**Description**\
Contains our projected regional CO2FFI emissions pathways at the R10 level under “current policies” (CurPol) and “current pledges” (CurPledge). “IMP-REN” indicates the AR6 illustrative mitigation pathway used as a reference in this work.

**Columns**

+-------------------+-------------------------------------------------------------------------------------------------+
| Column            | Description                                                                                     |
+===================+=================================================================================================+
| **model**         | The IAM from which the scenario ensemble was drawn to produce the underlying emissions pathway. |
+-------------------+-------------------------------------------------------------------------------------------------+
| **case**          | Scenario variant: **A** for CurPol (current policies), **E** for CurPledge (current pledges).   |
+-------------------+-------------------------------------------------------------------------------------------------+
| **r10**           | R10 region code.                                                                                |
+-------------------+-------------------------------------------------------------------------------------------------+
| **year**          | Year.                                                                                           |
+-------------------+-------------------------------------------------------------------------------------------------+
| **terr_GtCO2FFI** | Territorial (production-based) CO2 emissions from fossil fuel and industry (in Gt CO2).         |
+-------------------+-------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## 11. `11_curpol_curpledge_impren_temp.csv`

**Description**\
Contains global mean temperature (GMT) anomaly projections (relative to 1850–1900) under “current policies” (CurPol) and “current pledges” (CurPledge), generated using the simple climate model FaIR.

**Columns**

+--------------+-------------------------------------------------------------------------------------------------+
| Column       | Description                                                                                     |
+==============+=================================================================================================+
| **model**    | The IAM from which the scenario ensemble was drawn to produce the underlying emissions pathway. |
+--------------+-------------------------------------------------------------------------------------------------+
| **case**     | Scenario variant: **A** for CurPol, **E** for CurPledge.                                        |
+--------------+-------------------------------------------------------------------------------------------------+
| **quantile** | Temperature response quantile (e.g., 0.17, 0.50, 0.83) from FaIR to capture uncertainty ranges. |
+--------------+-------------------------------------------------------------------------------------------------+
| **year**     | Year.                                                                                           |
+--------------+-------------------------------------------------------------------------------------------------+
| **GMT**      | Global Mean Temperature anomaly (in °C) relative to the 1850–1900 baseline.                     |
+--------------+-------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## 12. `12_r10_exp_heatwave_emf.csv`

**Description**\
Provides estimates for changes in lifetime exposure to extreme heatwaves for different birth cohorts relative to the AR6 IMP-REN scenario. Additional (years) and multiplicative (factor) changes are relative to IMP-REN are shown, alongside the reference IMP-REN lifetime exposure estimates. The median (0.5), 33rd percentile (0.33), and 66th percentile (0.66) values capture uncertainty across both temperature outcomes and exposure estimates.

**Columns**

+---------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Column                                                                                                        | Description                                                                                                                        |
+===============================================================================================================+====================================================================================================================================+
| **birth_year**                                                                                                | The birth year of the cohort.                                                                                                      |
+---------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| **r10**                                                                                                       | R10 region code.                                                                                                                   |
+---------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| **case**                                                                                                      | Scenario variant: **A** for CurPol, **E** for CurPledge.                                                                           |
+---------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| **add_impren_0.5**,<br/>**add_impren_0.33**,<br/>**add_impren_0.66**                                          | Additional lifetime years exposed to extreme heatwaves, relative to the IMP-REN scenario, at the 50th, 33rd, and 66th percentiles. |
+---------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| **emf_impren_0.5**,<br/>**emf_impren_0.33**,<br/>**emf_impren_0.66**                                          | Multiplicative factor change in lifetime years with extreme heatwaves, relative to IMP-REN, for each percentile.                   |
+---------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| **lifetime_exposure_impren_0.5**,<br/>**lifetime_exposure_impren_0.33**,<br/>**lifetime_exposure_impren_0.6** | Baseline lifetime years with extreme heatwaves under the IMP-REN scenario, at the 50th, 33rd, and 66th percentiles.                |
+---------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## 13. `13_r10_curpol_curpledge_impren_rcbyear.csv`

**Description**\
Contains yearly regional remaining carbon budget calculations under CurPol and CurPledge scenarios. Data indicates when (and by how much) global budgets are exceeded, as well as each region’s share of that exceedance.

**Columns**

+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Column                      | Description                                                                                                                                                                   |
+=============================+===============================================================================================================================================================================+
| **model**                   | The IAM from which the scenario ensemble was drawn to produce the underlying emissions pathway.                                                                               |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **case**                    | Scenario variant: **A** for CurPol, **E** for CurPledge.                                                                                                                      |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **r10**                     | R10 region code.                                                                                                                                                              |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **year**                    | Year.                                                                                                                                                                         |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **terr_GtCO2FFI**           | Territorial (production-based) CO2 emissions from fossil fuel and industry (in GtCO2) in that year.                                                                           |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **allocation**              | Allocation approach category.                                                                                                                                                 |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **ppp_pf**                  | Defines whether PPP or MER GDP data is used, for allocation approaches that also consider capability, and which penalty function.                                             |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **rcbyear**                 | The remaining carbon budget (in Gt CO2) for the region in that year, under the specified scenario/allocation.                                                                 |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **scenexceedanceyear**      | The global scenario exceedance of the carbon budget (in Gt CO2) in that year.                                                                                                 |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **debtyear**                | The regional carbon debt (in Gt CO2) in that year, under the specified scenario/allocation.                                                                                   |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **scenexceedanceshareyear** | The region’s share (%) of the total global scenario exceedance in that year, under the specified scenario/allocation. This defines the region's responsibility for overshoot. |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **pop**                     | Population for the region in that year.                                                                                                                                       |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## 14. `14_r10_curpol_curpledge_impren_debt.csv`

**Description**\
Contains regional net-zero carbon debt calculations (or credit, if in surplus), along with population estimates enabling per capita drawdown obligation calculations, under CurPol and CurPledge scenarios.

**Columns**

+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Column                 | Description                                                                                                                                                  |
+========================+==============================================================================================================================================================+
| **model**              | The IAM from which the scenario ensemble was drawn to produce the underlying emissions pathway.                                                              |
+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **r10**                | R10 region code.                                                                                                                                             |
+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **case**               | Scenario variant: **A** = CurPol, **E** = CurPledge.                                                                                                         |
+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **allocation**         | Allocation approach category.                                                                                                                                |
+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **ppp_pf**             | Defines whether PPP or MER GDP data is used, for allocation approaches that also consider capability, and which penalty function.                            |
+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **rcb2100**            | Regional remaining carbon budget at net-zero CO2-FFI under the specified scenario/allocation (in Gt CO2). A negative value implies a “net-zero carbon debt”. |
+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **pop_cmltv_rem_2025** | Cumulative population from 2025–2100, used to calculate per capita carbon drawdown obligations.                                                              |
+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## Contact

For more information, please contact **Setu Pelz** at [pelz\@iiasa.ac.at](mailto:pelz@iiasa.ac.at).

------------------------------------------------------------------------

**End of README**\
\`\`\`
